---
title: "HRT101"
subtitle: "Introduction to Health Research"
author: "Md. Jubayer Hossain <br/> Founder, CHIRAL Bangladesh"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  xaringan::moon_reader:
    css: ["default", "css/chiral.css", "css/chiral-fonts.css"]
    lib_dir: libs
    nature:
      ratio: 16:9
      highlightStyle: atelier-lakeside-light
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
options(knitr.table.format = "html") 
knitr::opts_chunk$set(warning = FALSE, message = FALSE, 
  comment = NA, dpi = 300,
  fig.align = "center", out.width = "65%", cache = FALSE)

library(ymlthis)
library(tidyverse)
library(xaringanExtra)
library(palmerpenguins)
xaringanExtra::use_panelset()
xaringanExtra::use_share_again()
xaringanExtra::style_share_again(
  share_buttons = c("twitter", "linkedin", "pocket")
)
```

## Agenda 
- Literature Databases
- Literature Searching Strategies


---
class: inverse center middle

# Literature Databases



---
## What are Literature Databases? 


- Literature Databases are used to identify articles from peer-reviewed journals and other types of periodicals. 


--

- These databases are created by companies and other entities and are subscribed to by or licensed to academic and other institutions.


--

- In general, databases provide general information about individual articles and other content, such as the article title, author name, date of publication, descriptor words, and article summary (abstract).


--


- Major database producers provide a lot more details, and can allow the use of quite sophisticated searching strategies so that you can find the perfect paper.
.footnote[
[Source: Illinois Library; Accessed January 11, 2022, at https://guides.library.illinois.edu/](#)
]





---
class: inverse center middle

# Smart Google Searching 


---
## Smart Goolge: Search Tips 
- Conduct advanced searches into two ways 
  - By integrating Advanced Search Operators(ASO) into the search
  - By using the search engine's dedicated advance search page
.footnote[
[Source: Google; Accessed January 11, 2022, at https://developers.google.com/search/docs/advanced/]()
]

---
## Smart Google Searching: Advanced Search Tips 
- Specify exact phrases using quotation marks 
  - "mental health"

--

- Exclude a word using the minus sign 
  - "mental health" - children 
  
--

- Broaden your search using the OR operator 
  - "cell phones" OR "mobile phones"

--

- Narrow down your search using AND operator 
  - "mental health" AND "cell phones"


---
## Smart Google Searching: Advanced Search Operators 
- Add operators to searches to help narrow down results 
- Use operators not readily available from the Advanced Search Page


---
## Smart Google Searching: Advanced Search Operators - Site 
- site: 
  - Limits search results to a website or domain 
- Examples 
  - site:.gov - limits results to government websites 
  - site:.edu - limits results to educational websites 
  - site:.org - limits results to organizational websites 
  - site:cdc.gov - limits results to the CDC within government websites
  - site:.bd - limits results to websites in the country Bangladesh

---
## Smart Google Searching: Advanced Search Operators - Filetype 
- filetype:
  - Limits search results to .pdf, .ppt, .xls, .doc, etc
- Examples
  - filetype:ppt - Finds only powerpoint slides
  - filetype:pdf - Finds only pdf files
  - filetype:doc - Finds only word documents 
  - filetype:xls - Finds only excel files
  - filetype:ppt AND "lung cancer"

---
## Smart Google Searching: Advanced Search Operators - Combinations  
- Example of several operators in one search
  - filtetype:pdf site:bd "coronavirus"
    - Finds only PDF articles about corona virus hon Bangladeshi websites


---
## Smart Google Searching: Filters and Limits   
- Limit to:
  - Custom date range 
  - Date attached  to record 
  - Sort results 
  
- Example:
  - filtetype:pdf site:bd "coronavirus" 
  - Customize results by date 




---
class: inverse center middle

# Developing a Health Research Topic


---
## Start Somewhere


- Your interest or background 
  - course topic 

--

- Professional organization or government agency hot topics 
  - American Nursing Association 
  - National Institute of Health 
  - World Health Organization


--


- What's happen related to health in your geographical area of study? 
  - News, local initiatives, local organizations, etc. 


---
## Smart Google Searching: Brainstorming Trick

- Government Sites -  **site:.gov (topic AND topic)**

--


-  Organizational Sites - **site:.org (topic AND topic)**


--


- Educational Sites - **site:.edu (topic AND topic)**


---
## Smart Google Searching : A Practical Example

- What is the broad topic?
  - Maternal death

--

- Who does it impact? or who could it impact?
  - Expecting mothers, children/physicians/healthcare professionals


--

- When does this matter? At what time are you interested in this topic?
  - Last 5- 10 years


--

- Where do you want to focus?
  - Ohio
  
--

- Searching Strategies - **site:.gov (topic AND geography)**
  - site:.gov (maternal death AND ohio)
 

---
## Framing Possible Research Question

- Search Results
  - Pregnancy related mortality has been steady increasing in the US since 1987
  - 408 pregnancy associated deaths in Ohio between 2008-2014, most of which postpartum.
 
**Research Question:**
In Ohio, what disparties among expecting women are associated with maternal death(pregnancy related mortality)? 


---
## Is Your Research Question Answerable?

**Research Question:**
In Ohio, what disparties among expecting women are associated with maternal death(pregnancy related mortality)? 



---
class: inverse center middle

# Using Google Scholar 


---
## Google Scholar: Overview 
- Google Scholar provides a simple way to broadly search for scholarly literature. 
- From one place, you can search across many disciplines and sources: articles, theses, books, abstracts and court opinions, from academic publishers, professional societies, online repositories, universities and other web sites.
-  Google Scholar helps you find relevant work across the world of scholarly research.
.footnote[
[Source: Google Scholar; Accessed January 11, 2022, at https://scholar.google.com/intl/en/scholar/about.html]()
]


---
## Google Scholar: Why Use It?
- Relevancy(relevant hits at the top of the list; tend to be older)
- Web-based materials not in other databases
- Searches a broad cross-section of subjects and disciplines
- "Cited by" links to works that cite a particular book or article 
- Links to University Library 

---
## Google Scholar: Advantages 

- Google Scholar is familiar and relatively simple to use, much like Google.
- Google Scholar allows users to search for a find a wide variety of materials including articles, books, "grey literature" like conference proceedings on a vast number of topics.
- Google Scholar allows for you to see articles related to the one that might interest you, how many times an article has been cited and by whom, and provides citations for articles in a number of styles.
- Google Scholar can display links to articles and books held through ECU Libraries. For more information, see Using Google Scholar from Home tab.
- Google Scholar allows you to save both citations and articles to read later.

.footnote[
[Source:East Carolina University Libraries; Accessed January 11, 2022, at https://libguides.ecu.edu/]()
]


---
## Google Scholar: Disadvantages

- Google Scholar's coverage is is wide-ranging but not comprehensive. It can be a research source, but should not be the only source you use.
- Google Scholar does not provide the criteria for what makes its results "scholarly". Results are often vary in quality and it is up to the researcher to determine which of the results are suitable for their purposes.
- Google Scholar does not allow users to limit results to either peer reviewed or full text materials or by discipline.
- Google Scholar does not provide notice of when its materials are updated.
- Google Scholar's citation tracker can be difficult to use and inaccurate.

.footnote[
[Source:East Carolina University Libraries; Accessed January 11, 2022, at https://libguides.ecu.edu/]()
]


---
## Google Scholar: Content - Use with Caution!
- Frequency of updates unknown 
- Gaps in coverage 
- May omit year, issu numbers, or journal titles
- Bias towards older literature, much of which is not full text

.footnote[
[Source: Mayr, P., & Walter, A. K. (2008). Studying journal coverage in Google Scholar. Journal of Library Administration, 47(1-2), 81-99]()
]

---
## Default Google Scholar Search Settings
- Not case sensitive - capital letters of search terms are ignored
- `AND` - search terms are automatically combined using AND
- keyword - searches the full text of scholarly material, including citation and abstract


---
## Options to Refine Your Search - 1
- Synonyms
  - Google automatically searches for matching and similar meaning words
  - tourism finds tourist
- Phrase searching
  - use quotation marks around phrases
  - “hearing loss”
- OR
 - Results include either search term. OR must be in capital letters
 - ipod OR mp3
- Exclude
  - use `–` immediately before a search term you want to exclude
  -  ipod – itunes
- Include
  - use + immediately before automatically excluded search terms that you want included
  - +the 
- Intitle
   - Finds results with your search term in the document title
   - intitle:mp3





---
## Options to Refine Your Search - 2
- Author 
  - Finds results with your search term as the document author
  - author:Jones

- Date range
  -  To change from Any time, select an option from left side of the results screen

- Document type
  -  Choose Articles or Case law or My library, or deselect include patents


--- 
## Advanced Scholar Search


--- 
## Interpreting the Results Screen


--- 
## Creating Literature Matrix using Librray 









---
class: inverse center middle

# Using PubMed


---
## PubMed Overview 
- Produced by the National Library of Medicines(NLM)
- One of the largest biomedical literature databases
- Provide free access to MEDLINE 
- Covers medicines, public health, nursing, dentistry and much more

.footnote[
[Source: PubMed; Accessed January 11, 2022, at https://pubmed.ncbi.nlm.nih.gov/]()
]


---
## Difference Between MEDLINE and PubMed 
- MEDLINE is NLM's database of journal citations and abstracts for biomedical literature.
- MEDLINE citations have been indexed and reviewed for accuracy
- Medical Subject Headings(MeSH) are  specialized subject headings (controlled vocabulary) used to index citations in MEDLINE



---
class: inverse center middle

# PubMed: Basics of Searching

---
## PubMed Search: Searching Information
- Looking for high-quality articles to answer specific questions 
- Scoping the literature to see what’s been published 
- Conducting an in-depth literature review 


---
## Common Searching Techniques 
- Boolean operators AND & OR 
- Nesting to group similar terms 
- Truncation for words with multiple endings 
- Quotes for phrases 


---
## Search Scenario -1 
> Possible risk of mobile phones causing cancer in children 



---
## Search Scenario -2 
> How has the literature changed in the last 15 years regarding the relationship between mobile phones and cancer in children? 


---
## Boolean Operators 
- AND, OR & NOT

---
## Combined Terms with AND 
- Cancer AND children AND mobile phones => Find articles that include all three terms. 


---
## Combined Terms with OR 
- Cancer AND children AND mobile phones => Find articles that include all three terms. 

- Mobile phones OR smartphones OR cell phones
  - Find articles on any of these topics 
  - Use OR with synonyms or similar terms to expand the number of results. 


---
## Combined Terms with NOT 
- Cancer NOT leukemia 
  - It looks for articles about cancer but removes articles that talk about leukemia. 

---
## Caution about NOT 
- Children NOT adults 
  - Removes citations that could be relevant 
  - Miss article that addresses adults and children 


---
## Use of Boolean Operators 
- Use all caps for ANDs and ORs.

---
## Nesting
- Children AND cancer AND mobile phones OR smartphones OR cell phones
  - PubMed uses an algorithm to search 

- Children AND cancer AND mobile phones OR smartphones OR cell phones
  - Children AND cancer AND mobile phones => PubMed reads from left to right 
  - OR smartphones OR cell phones => OR articles on smartphones OR articles on cell phones

---
## Nesting Parentheses 
- Cancer AND children ANd (mobile phones OR smartphones OR cell phones)
- Phrasing 
  - PubMed automatically adds an AND between words 
  - Can cause problems with phrases like cell towers

- Put double quotation marks around phrases
  - “Cell phones”, “mobile phones”
  - You don’t need quotes around single words such as smartphones

- Truncation Symbol
  - The PubMed truncation symbol is the asterisk(*) 
  - Truncation uses word stems and matches various words endings
  


---
class: inverse center middle

# PubMed: Building a Search


---
## Systematic Approach for Finding Relevant Articles 
- Use a combination of Medical Subject Heading(MeSH) and Keywords
- Incorporate Boolean Operators, truncation, and field tags
- Run your search in PubMed


---
## Research Question and Key Concepts 
> How are mobile apps currently being used to help individuals with high blood pressure eat a healthier diet?  

- Key Concepts: mobile apps AND diet AND blood pressure 


---
## Searching Strategies 
- **Research Question:**How are mobile apps currently being used to help individuals with high blood pressure eat a healthier diet?  

- **Concept 1:** Mobile apps 
  - **Keywords:** mobile application(s), mobile technology(ies), mHealth

- **Concept 2:** Diet 
  - **Keywords:** diet, nutrition
  
- **Concept 3:** Blood pressure 
  - **Keywords:** hypertention, high blood pressure


---
## Step 1: Identify relevant Mesh for research question
> **MeSH** refers to the specialized subject headings, or controlled vocabulary, used in **Medline**. All Medline articles are indexed with his vocabulary


---
class: center, middle

# Thanks!

Find me: <br/>
Email: [contact.jubayerhossain@gmail.com](#)<br/>
Website: https://jhossain.com/<br/> 
Github: https://github.com/hossainlab<br/>